improved readability of OpenASIP.tex with minor grammar fixes
cpc/openasip pull request #178
Opened 2022-09-13 22:17 UTC by lightning-singh

Very sorry it took longer than it should have. Please advise me if there are any problems with this pull request.

2022-09-19 07:16 UTC, karihepola commented
Thanks for the contribution, much appreciated! Your fork seems to be a few commits behind the branch during which there have been modifications to the manual, eg. "/tce/" paths have been updated to "/openasip/". Could you rebase your fork to get these changes pulled in? Thanks!

2022-09-20 08:05 UTC, karihepola requested changes
Hi, apparently the merge to the upstream branch did not pull in the corrections to the paths. Could you fix these to the new ones where /tce/ is replaced with /openasip/ ? Thanks!

2022-09-20 08:05 UTC, karihepola commented on tce/doc/man/OpenASIP/OpenASIP.tex
> +  cp $(tce-config --prefix)/share/tce/data/mach/minimal.adf start.adf
Replace /tce/ with /openasip/

2022-09-20 08:05 UTC, karihepola commented on tce/doc/man/OpenASIP/OpenASIP.tex
> +OpenASIP installation path (PREFIX/share/tce/hdb/asic\_130nm\_1.5V.hdb), make sure
Replace /tce/ with /openasip/

2022-09-20 08:05 UTC, karihepola commented on tce/doc/man/OpenASIP/OpenASIP.tex
> +%\textit{Browse... (installation\_path)/share/tce/icdecoder\_plugins/base/
Replace /tce/ with /openasip/

2022-09-20 08:05 UTC, karihepola commented on tce/doc/man/OpenASIP/OpenASIP.tex
> +cp $(tce-config --prefix)/share/tce/data/mach/minimal_with_stdout.adf .
Replace /tce/ with /openasip/

2022-09-20 08:05 UTC, karihepola commented on tce/doc/man/OpenASIP/OpenASIP.tex
> +\emph{fpu\_embedded.hdb}, which can be found at \emph{PREFIX/share/tce/hdb/fpu\_embedded.hdb}.
Replace /tce/ with /openasip/

2022-09-20 08:05 UTC, karihepola commented on tce/doc/man/OpenASIP/OpenASIP.tex
> +A set of half-precision arithmetic units is included with tce in \emph{PREFIX/share/tce/hdb/fpu\_half.hdb}. In C and C++,
Replace /tce/ with /openasip/

2022-09-20 08:05 UTC, karihepola commented on tce/doc/man/OpenASIP/OpenASIP.tex
> +\shellcmd{cp \$(tce-config -{}-prefix)/share/tce/data/mach/minimal.adf hwloop.adf}
Replace /tce/ with /openasip/

2022-09-20 08:05 UTC, karihepola commented on tce/doc/man/OpenASIP/OpenASIP.tex
> +  cp $(tce-config --prefix)/share/tce/data/mach/riscv.adf start.adf
Replace /tce/ with /openasip/

2022-09-20 08:05 UTC, karihepola commented on tce/doc/man/OpenASIP/OpenASIP.tex
> +   example /usr/local/share/tce).
Replace /tce/ with /openasip/

2022-09-20 08:05 UTC, karihepola commented on tce/doc/man/OpenASIP/OpenASIP.tex
> +   example /usr/local/share/tce).
Replace /tce/ with /openasip/

2022-11-14 11:42 UTC, pjaaskel commented
Is this to be merged?

2022-11-14 15:29 UTC, closed without merging