building for Ubuntu24.04
cpc/openasip pull request #276
Opened 2024-12-12 11:09 UTC by postoroniy

2024-12-12 11:10 UTC, postoroniy commented
╰─ oa-selftest -v                                                                                                                                                                          ─╯
Testing OpenASIP installation, this can take up to two hours.
Time to go for a lunch? Use -v to see the progress.
test_noOpt (__main__.TestCompiler.test_noOpt)
Test C compilation with -O0 ... ok
test_opt (__main__.TestCompiler.test_opt)
Test C compilation with -O3 ... ok
test_custom_operation_from_c_code (__main__.TestCustomOps.test_custom_operation_from_c_code)
Test creating a simple custom operation with simulation code and ... ok
test_basic_plugins (__main__.TestExplorer.test_basic_plugins)
Test the ImplementationSelector and Evaluate explorer plugins (this ... ok
test_default_plugins_found (__main__.TestExplorer.test_default_plugins_found)
Check that the default Explorer plugins are listed. ... ok
test_proge_and_pig (__main__.TestProGeAndPIG.test_proge_and_pig)
Test the processor generator and the program image generator (with ... ok
test_compiled_simulation (__main__.TestSimulator.test_compiled_simulation)
Test the compiled engine of the simulator ... ok
test_debugging_simulation (__main__.TestSimulator.test_debugging_simulation)
Test the debugging engine of the simulator ... ok

----------------------------------------------------------------------
Ran 8 tests in 94.155s

OK

2024-12-12 12:12 UTC, pjaaskel requested changes

2024-12-12 12:12 UTC, pjaaskel commented on README.md
> +This version of Ubuntu has only libwxgtk3.2 and it requires to build wxGTK manualy
Did you check how far is 3.2 from 3.0 API-wise? Would it be difficult to fix OpenASIP code base to support it? Unfortunately 20.04 nor 22.04 do not support it, so we'd need to #ifdef-support the both versions.

2024-12-12 12:12 UTC, pjaaskel commented on README.md
> +It could be impossible to build with default libboost-all-dev, please use version 1.74
```suggestion
The default libboost installed by Ubuntu 24.04 is not yet supported by OpenASIP, however, the version 1.74 works:
```

2024-12-12 12:12 UTC, pjaaskel commented on README.md
>  Ubuntu 20.04+ / Debian 11
```suggestion
Ubuntu 20.04, 22.04 and Debian 11
```

2025-06-04 13:53 UTC, pjaaskel commented
24.04 fixed in main.

2025-06-04 13:53 UTC, closed without merging